name: plas_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  razorpay_flutter: ^1.3.6
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  location: ^6.0.1
  cloud_firestore: ^4.14.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo2.png"

flutter:
  uses-material-design: true
  assets:
    - images/
