// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0lVTcmsvgRlozKckH0vAaRW8oMZoxGM',
    appId: '1:884275839977:web:0313a9ae2ae6ef28804178',
    messagingSenderId: '884275839977',
    projectId: 'plastrack-ec49b',
    authDomain: 'plastrack-ec49b.firebaseapp.com',
    storageBucket: 'plastrack-ec49b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKE7W0RvPQdmaiHkpL5tcUPMH9x0ErUao',
    appId: '1:884275839977:android:2c5105d0e5b34528804178',
    messagingSenderId: '884275839977',
    projectId: 'plastrack-ec49b',
    storageBucket: 'plastrack-ec49b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8NWUMOt02Vkg2Jr1GoNyzOkv7_6hrrFo',
    appId: '1:884275839977:ios:250523f54b2574dd804178',
    messagingSenderId: '884275839977',
    projectId: 'plastrack-ec49b',
    storageBucket: 'plastrack-ec49b.appspot.com',
    iosBundleId: 'com.example.plasTrack',
  );
}
